services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
      GF_INSTALL_PLUGINS: novatec-sdg-panel
    restart: always

  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb:/var/lib/influxdb2
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_BUCKET: bitburner
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_RETENTION: 1w # One Week
      DOCKER_INFLUXDB_INIT_USERNAME: initusername
    restart: always

  telegraf:
    image: telegraf
    ports:
      - "8080:8080"
    environment:
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
    volumes:
      - "./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf"
    restart: always

volumes:
  grafana:
  influxdb:
