{
 "title": "BitBurner",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Player Money",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_listener_v2\" and\r\n    r._field == \"money\"\r\n  )"
    }
   ]
  },
  {
   "title": "Hacked Servers",
   "type": "bargauge",
   "gridPos": { "h": 47, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field =~ /owned|hacked|usedRam|maxRam/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.owned == 0 and r.hacked == 1)\r\n  |> group()\r\n  |> unique(column: \"server\")\r\n  |> map(fn: (r) => ({ server: r.server, usedPercent: float(v: r.usedRam) / float(v: r.maxRam) * 100.0}))\r\n  |> drop(columns: [\"_field\", \"_measurement\", \"host\", \"_time\", \"_value\", \"_start\", \"_stop\", \"hacked\", \"owned\"])\r\n  |> sort(columns: [\"usedRam\"], desc: true)\r\n"
    }
   ]
  },
  {
   "title": "HGW running statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_listener_v2\" and\r\n    r.hgw == \"weaken\" or r.hgw == \"grow\" or r.hgw == \"hack\"\r\n  )\r\n  |> aggregateWindow(every: 1s, fn: sum)\r\n  |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "Target Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_listener_v2\" and\r\n    exists r.target\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: max)\r\n"
    }
   ]
  },
  {
   "title": "Owned Servers",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 13, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field =~ /owned|hacked|usedRam|maxRam/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.owned == 1 and r.hacked == 1)\r\n  |> group()\r\n  |> unique(column: \"server\")\r\n  |> map(fn: (r) => ({ server: r.server, usedPercent: float(v: r.usedRam) / float(v: r.maxRam) * 100.0}))\r\n  |> drop(columns: [\"_field\", \"_measurement\", \"host\", \"_time\", \"_value\", \"_start\", \"_stop\", \"hacked\", \"owned\"])\r\n  |> sort(columns: [\"server\", \"usedRam\"], desc: true)\r\n"
    }
   ]
  }
 ]
}